# Generated by Django 3.2.8 on 2021-10-23 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_todo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='User',
            new_name='user',
        ),
    ]
